stages:
  - compile
  - package

build-ubuntu:
  stage: compile
  image: burningdaylight/ubuntu-latest-devel
  script:
    - mkdir -p ${CI_BUILD_NAME}
    - rm -f ${CI_BUILD_NAME}/src/gui/Olga ${CI_BUILD_NAME}/src/gui/main.o
    - find ${CI_BUILD_NAME} -name "Makefile*" -delete
    - cd ${CI_BUILD_NAME}; qmake ..; make
  cache:
    paths:
    - ${CI_BUILD_NAME}/
  artifacts:
    expire_in: 1 day
    paths:
      - ${CI_BUILD_NAME}/src/gui/Olga
      - ${CI_BUILD_NAME}/src/irmsd/libirmsd.so.1.0.0

build-win64:
  stage: compile
  image: burningdaylight/mingw-arch-mol
  script:
    - mkdir -p ${CI_BUILD_NAME}
    - rm -f ${CI_BUILD_NAME}/src/gui/release/Olga.exe ${CI_BUILD_NAME}/src/gui/release/main.o
    - find ${CI_BUILD_NAME} -name "Makefile*" -delete
    - cd ${CI_BUILD_NAME}; x86_64-w64-mingw32-qmake-qt5 ..; make
  cache:
    paths:
    - ${CI_BUILD_NAME}/
  artifacts:
    expire_in: 1 day
    paths:
      - ${CI_BUILD_NAME}/src/gui/release/Olga.exe
      - ${CI_BUILD_NAME}/src/irmsd/release/irmsd.dll


build-win32:
  stage: compile
  image: burningdaylight/mingw-arch-mol
  script:
    - mkdir -p ${CI_BUILD_NAME}
    - rm -f ${CI_BUILD_NAME}/src/gui/release/Olga.exe ${CI_BUILD_NAME}/src/gui/release/main.o;
    - find ${CI_BUILD_NAME} -name "Makefile*" -delete
    - cd ${CI_BUILD_NAME}; i686-w64-mingw32-qmake-qt5 ..; make
  cache:
    paths:
    - ${CI_BUILD_NAME}/
  artifacts:
    expire_in: 1 day
    paths:
      - ${CI_BUILD_NAME}/src/gui/release/Olga.exe
      - ${CI_BUILD_NAME}/src/irmsd/release/irmsd.dll

pack-ubuntu:
  stage: package
  image: burningdaylight/ubuntu-latest-devel
  script:
    - ./src/pack_ubuntu.sh build-ubuntu Olga
  dependencies:
    - build-ubuntu
  needs: ["build-ubuntu"]
  artifacts:
    expire_in: 1 week
    name: "Olga_ubuntu18.04_${CI_BUILD_REF_NAME}-${CI_BUILD_REF:0:8}"
    paths:
      - Olga

pack-win64:
  stage: package
  image: burningdaylight/mingw-arch-mol
  script:
    - ./src/pack_mingw.sh build-win64 /usr/x86_64-w64-mingw32 Olga
  dependencies:
    - build-win64
  needs: ["build-win64"]
  artifacts:
    name: "Olga_win64_${CI_BUILD_REF_NAME}-${CI_BUILD_REF:0:8}"
    expire_in: 1 week
    paths:
      - Olga

pack-win32:
  stage: package
  image: burningdaylight/mingw-arch-mol
  script:
    - ./src/pack_mingw.sh build-win32 /usr/i686-w64-mingw32 Olga
  dependencies:
    - build-win32
  needs: ["build-win32"]
  artifacts:
    expire_in: 1 week
    name: "Olga_win32_${CI_BUILD_REF_NAME}-${CI_BUILD_REF:0:8}"
    paths:
      - Olga

#test:
#  stage: test
#  script:
#    - ./runmytests.sh
